### ISSUE TITLE
[1.20.x - Fabric] Crash when trying to scoop Quicksand up in Buckets

### ISSUE THREAD

**Issue by Lv44EnderShaman** [Shnupbups/quicksand#11]
Thank you for the update to 1.20. Seems the feature to scoop up Quicksand in buckets is causing a crash. Attempting to do so causes a crash with the following error in the log:

> [04:51:30] [Render thread/ERROR]: Unreported exception thrown!
java.lang.AbstractMethodError: Receiver class com.shnupbups.quicksand.block.QuicksandBlock does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_1799 method_9700(net.minecraft.class_1936, net.minecraft.class_2338, net.minecraft.class_2680)' of interface net.minecraft.class_2263.

Might not be inheriting the ability to be scooped up like a fluid like Powder Snow, it seems.

**Comment by Shnupbups** [comment]
Will look into tomorrow

**Comment by Shnupbups** [comment]
ah, you're using 1.20.1. This version only works on 1.20.2.

**Comment by Shnupbups** [comment]
Released a 1.20.1 backport so you can use that :)
