### ISSUE TITLE
[1.19] Server thread hang

### ISSUE THREAD

**Issue by Flypaste** [Shnupbups/quicksand#4]
I'm trying quicksand in 1.19, and it freezes the server thread. I don't have a crash report or log because it doesn't create one. Removing quicksand from the game fixes the problem from happening. I used worldgen seed -8483139313213194642 to reproduce. You spawn and then walk 32 blocks south along the beach, and by the time you get to the pig, the server has died. I also have ecologics, not sure if the presence of that mod changes whether quicksand hangs the game so quickly on this seed.

**Comment by Shnupbups** [comment]
Should be fixed in 1.2.1
